version: '3.8'

services:
  # Sandbox container for code execution
  sandbox:
    build:
      context: ./docker/sandbox
      dockerfile: Dockerfile
    image: yz-sandbox
    container_name: yz-sandbox
    privileged: true  # Required for isolate to work properly
    volumes:
      - ./backend:/app/backend:ro  # Mount backend code
      - /tmp/yz-executions:/tmp/yz-executions  # Temporary execution space
    networks:
      - yz-network
    restart: unless-stopped
    environment:
      - ISOLATE_CONFIG=/etc/isolate.conf
    command: tail -f /dev/null  # Keep container running

  # Backend API server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yz-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker API access
    networks:
      - yz-network
    depends_on:
      - sandbox
    environment:
      - PORT=8080
      - SANDBOX_CONTAINER=yz-sandbox
      - YZ_COMPILER_PATH=/usr/local/bin/yzc
    restart: unless-stopped

  # Frontend web server (simple static server)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yz-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - yz-network
    depends_on:
      - backend
    environment:
      - PORT=3000
      - API_URL=http://backend:8080
    restart: unless-stopped

networks:
  yz-network:
    driver: bridge

volumes:
  yz-executions:
    driver: local
